version: "3.7"
services:
  nginx_proxy:
    image: nginx_proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./../auth_file:/usr/local/nginx/conf/auth_file
    environment:
      - TZ=Etc/UTC
    restart: always
    ports:
      - "8888:8888"
