name: Test - Container Image Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build the Docker image
        run: |
          docker-compose -f docker-compose.yaml up -d --build
          docker images -a

      - name: Test with curl
        run: |
          nginx_proxy_ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx_proxy)
          err=1
          count=0
          while [[ $err != 0 ]]; do
            curl https://www.google.com -svo /dev/null -x $nginx_proxy_ip:8888
            err=$?
            [[ $err == 0 ]] && exit 0
            count=$(( count + 1 ))
            [[ $count -ge 5 ]] && exit 1
          done

      - name: Stop containers and show logs
        if: always()
        run: |
          docker exec -i nginx_proxy cat /var/log/nginx_errors.log
          docker exec -i nginx_proxy cat /var/log/nginx_access.log
          docker-compose -f docker-compose.yaml down
